### ISSUE TITLE
Unable to add tags to issues [Meta] [Issue Tracker] [We Need Tags]

### ISSUE THREAD

**Issue by vincentzhang96** [vincentzhang96/CommunityDiscord#4]
Title.

**Comment by grey21man** [comment]
Maybe something like room specific [Lounge]

**Comment by Aelphaeis** [comment]
I've made Issue Tracker and Meta tags, what other tags do you think should be created.

**Comment by vincentzhang96** [comment]
We dont have the ability to _add_ or manage tags on issues

**Comment by vincentzhang96** [comment]
Fixed~
