### ISSUE TITLE
Requesting delete for this issue ( no permission)

### ISSUE THREAD

**Issue by LEJAC11** [vincentzhang96/CommunityDiscord#5]
Nevermind It. I changed my mind. Thanks

**Comment by Alukah** [comment]
Can you give an example of any topic you tried to discuss (and used @moderators) and got ignored? I checked my recent mentions and the only @ I have from you was to discuss Jon's new alt.

**Comment by Aelphaeis** [comment]
You cannot delete issues. Once you make them they are permanent.
