### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by vincentzhang96** [vincentzhang96/CommunityDiscord#7]
If reactions shall be restricted, and if so, in which channel(s)?

As of right now, lounge, rules, party-recruitment, and trade have it disabled. Lounge temporarily for spam control, rules since that channel is purely for reference, the rest have no obvious need for them.

**Comment by ImMikeu** [comment]
I don't think they should be. Even spammed it isnt really intrusive.

**Comment by vincentzhang96** [comment]
I don't think it'll be an issue for any channel besides rules, since we don't want/need reactions to our rules nor have them break up the text blocks. I'm fine with allowing them.

**Comment by Donkay20** [comment]
Not an issue, aside from important channels.

**Comment by LEJAC11** [comment]
I dont mind it
